#ifndef KR_COMMON_PROTOBUF_LUA_GENERATOR_H_ 
#define KR_COMMON_PROTOBUF_LUA_GENERATOR_H_

#if defined(_MSC_VER) && (_MSC_VER >= 1200) 
#pragma once
#endif



#endif //KR_COMMON_PROTOBUF_LUA_GENERATOR_H_

